// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "agentpanelocx.h"

/////////////////////////////////////////////////////////////////////////////
// CAgentPanelOcx

IMPLEMENT_DYNCREATE(CAgentPanelOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAgentPanelOcx properties

/////////////////////////////////////////////////////////////////////////////
// CAgentPanelOcx operations

void CAgentPanelOcx::ActionLogon(LPCTSTR sAccount, LPCTSTR sPassword, short iLoginServerOpt, LPCTSTR sLoginServerHost)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sAccount, sPassword, iLoginServerOpt, sLoginServerHost);
}

void CAgentPanelOcx::ActionLogon2(LPCTSTR sCorp, LPCTSTR sAccount, LPCTSTR sPassword, short iLoginServerOpt, LPCTSTR sLoginServerHost)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCorp, sAccount, sPassword, iLoginServerOpt, sLoginServerHost);
}

void CAgentPanelOcx::ActionReset()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionLogout()
{
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionLogonAgain()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionCallDepartment(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionCallAgent(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionCallOtherAgent(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionCallPstn(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionCallExtNum(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionCallOtherDepartment(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionOnHook()
{
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionOffHook()
{
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionPark()
{
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionUnPark()
{
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionProcess()
{
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionUnProcess()
{
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionHold()
{
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionUnHold()
{
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionTransfer()
{
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionAutoTransfer()
{
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionStartMonit(LPCTSTR sAgentID, LPCTSTR sIP, LPCTSTR sPort)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sAgentID, sIP, sPort);
}

void CAgentPanelOcx::ActionStopMonit()
{
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionForceDisconnect(LPCTSTR sAgentID)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sAgentID);
}

void CAgentPanelOcx::ActionGetFullFreeAgentInfo()
{
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionGetGroupInfo()
{
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionGetOneGroupFreeAgentInfo(LPCTSTR sGroupName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sGroupName);
}

void CAgentPanelOcx::ActionGetTalkingAgent()
{
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionSendDTMF(short iDTMFCode)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iDTMFCode);
}

void CAgentPanelOcx::ActionChangePassword(LPCTSTR sAccount, LPCTSTR sOldPassword, LPCTSTR sNewPassword)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sAccount, sOldPassword, sNewPassword);
}

void CAgentPanelOcx::ActionChangeEarphoneVolume(short iNewVolume)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iNewVolume);
}

void CAgentPanelOcx::ActionChangeMicVolume(short iNewVolume)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iNewVolume);
}

void CAgentPanelOcx::ActionSendSMS(LPCTSTR sTargetNum, LPCTSTR sSMSContent)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sTargetNum, sSMSContent);
}

void CAgentPanelOcx::ActionSendChat(LPCTSTR sChatContent)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sChatContent);
}

void CAgentPanelOcx::ConfigPortSettings(BOOL bCustomizePort, long lAgentPort, long lAudioPort1, long lAudioPort2, BOOL bRequireTCPTransfer, BOOL bIsLanUser)
{
	static BYTE parms[] =
		VTS_BOOL VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_BOOL;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bCustomizePort, lAgentPort, lAudioPort1, lAudioPort2, bRequireTCPTransfer, bIsLanUser);
}

void CAgentPanelOcx::ConfigRecSettings(BOOL bLocalRecord)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bLocalRecord);
}

void CAgentPanelOcx::ConfigOutDialSettings(BOOL bAutoOffhook, BOOL bOutDialMobileAddZero, LPCTSTR sAreaNum, LPCTSTR sOneKeyNum)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BSTR VTS_BSTR;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bAutoOffhook, bOutDialMobileAddZero, sAreaNum, sOneKeyNum);
}

void CAgentPanelOcx::ConfigSoundSettings(BOOL bMicAutoCtrl, BOOL bEchoRemove, BOOL bMicBostUp, BOOL bUsePCSpeaker)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bMicAutoCtrl, bEchoRemove, bMicBostUp, bUsePCSpeaker);
}

short CAgentPanelOcx::GetLoginManner()
{
	short result;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetDeptment()
{
	CString result;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetCorp()
{
	CString result;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetCallType()
{
	short result;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetCallFrom()
{
	CString result;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetPrivateData()
{
	CString result;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetRecInvokeID()
{
	CString result;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetClientState()
{
	short result;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetLogonType()
{
	short result;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetCallPartyType()
{
	short result;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetAgentHasLogon()
{
	BOOL result;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::Initialize(short iVersionType, LPCTSTR sVersionNum)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		iVersionType, sVersionNum);
	return result;
}

void CAgentPanelOcx::Exit()
{
	InvokeHelper(0x33, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

short CAgentPanelOcx::GetRoleInCompany()
{
	short result;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetAgentAccount()
{
	CString result;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetIsCCNUser()
{
	BOOL result;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetAgentType()
{
	short result;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetIsSMSEnabled()
{
	BOOL result;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetAgentExtNum()
{
	CString result;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetAgentPhoneNo()
{
	CString result;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetManagerID()
{
	CString result;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetIsSuperAgent()
{
	BOOL result;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetIsMasterSuperAgent()
{
	BOOL result;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::ActionSendStrMsg(LPCTSTR cTargets, LPCTSTR cContent)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cTargets, cContent);
}

CString CAgentPanelOcx::GetRemindTime()
{
	CString result;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::ActionSettings()
{
	InvokeHelper(0x40, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionMonit()
{
	InvokeHelper(0x41, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionAgentOutDial(LPCTSTR sCallTarget, short iCallType)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x42, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget, iCallType);
}

BOOL CAgentPanelOcx::GetIsMonit()
{
	BOOL result;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetSMSParamsInfo()
{
	CString result;
	InvokeHelper(0x44, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetAllSettings()
{
	CString result;
	InvokeHelper(0x45, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetBriefStatisticInfo(LPCTSTR sDayTime)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		sDayTime);
	return result;
}

void CAgentPanelOcx::ActionSaveBriefStatisticInfo()
{
	InvokeHelper(0x47, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionSetMuteMode(BOOL bSetMute)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bSetMute);
}

void CAgentPanelOcx::ActionTransferToIVR(LPCTSTR sPrivateData, BOOL bUseDefaultTypes, LPCTSTR sLanguageType, LPCTSTR sOperationType, short iWorkingMode)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BSTR VTS_BSTR VTS_I2;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sPrivateData, bUseDefaultTypes, sLanguageType, sOperationType, iWorkingMode);
}

CString CAgentPanelOcx::GetTransferToIVRParamsInfo()
{
	CString result;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CAgentPanelOcx::GetIsCallFromACD()
{
	BOOL result;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::ActionUpdateSettings()
{
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CAgentPanelOcx::GetIsOutDialOpenURL()
{
	BOOL result;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

short CAgentPanelOcx::GetIVRReturn()
{
	short result;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::SetProductVersion(short iVersionType, LPCTSTR sVersionNum)
{
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iVersionType, sVersionNum);
}

CString CAgentPanelOcx::GetRecInvokePath()
{
	CString result;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetAgentID()
{
	CString result;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::SetOriginalData(LPCTSTR sOriginalData)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sOriginalData);
}

void CAgentPanelOcx::ActionOutDial(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::SetSelectGroup(LPCTSTR sGroup)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sGroup);
}

void CAgentPanelOcx::ActionAutoTransferEx(LPCTSTR sCallTarget)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCallTarget);
}

void CAgentPanelOcx::ActionOutDialWithRecSetting(LPCTSTR strTarget, LPCTSTR strRecPath)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strTarget, strRecPath);
}

void CAgentPanelOcx::ActionOffHookWithRecSetting(LPCTSTR sRecPath)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sRecPath);
}

BOOL CAgentPanelOcx::GetIsCallInOpenURL()
{
	BOOL result;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetParkReasons()
{
	CString result;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::SetParkReason(short iParkReasonID)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iParkReasonID);
}

void CAgentPanelOcx::SetCallerSendingInDialing(LPCTSTR sCaller)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sCaller);
}

void CAgentPanelOcx::ActionJoinOutDialMode(BOOL bJoinOutDialMode)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bJoinOutDialMode);
}

BOOL CAgentPanelOcx::GetIsOutDialMode()
{
	BOOL result;
	InvokeHelper(0x5d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CAgentPanelOcx::GetMoudleFilePath()
{
	CString result;
	InvokeHelper(0x5e, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CAgentPanelOcx::ActionSetMuteModeEx(long nDev, long nVolume, BOOL bSet)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x5f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nDev, nVolume, bSet);
}

// add by lh.wang date:2012.11.08 µÚÈý·½
void CAgentPanelOcx::ActionStartConference()
{
   InvokeHelper(0x60, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionEndConference()
{
   InvokeHelper(0x61, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CAgentPanelOcx::GetCanConference()
{
	BOOL  result = FALSE;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}
// end add 

void CAgentPanelOcx::StopPlayAgentID()
{
	InvokeHelper(0x63, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::ActionACDAutoLogin()
{
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAgentPanelOcx::SetLogonMode(short nLoginMode)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_EMPTY, NULL, parms, nLoginMode);
}