//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ICServingAgentClient.rc
//
#define IDR_MAINFRAME                   17
#define IDB_BMP_TRANSFER_TO_IVR_1       24
#define IDB_BMP_TRANSFER_TO_IVR_2       25
#define IDB_BMP_TRANSFER_TO_IVR_3       26
#define IDB_BMP_TRANSFER_TO_IVR_4       27
#define IDD_DLG_TRANSFER_TO_IVR         28
#define IDB_BMP_WHISHT_UP               31
#define IDB_BMP_WHISHT_DOWN             36
#define IDB_BMP_MINBAR_1                40
#define IDB_BMP_MINBAR_2                41
#define IDB_BMP_MINBAR_3                42
#define IDI_ICON_IEPREV_1               58
#define IDI_ICON_IECLOSEALL_1           59
#define IDI_ICON_IECLOSEALL_2           60
#define IDI_ICON_IECLOSEALL_3           61
#define IDI_ICON_IELAST_1               62
#define IDI_ICON_IELAST_2               63
#define IDI_ICON_IELAST_3               64
#define IDI_ICON_IEFIRST_2              65
#define IDI_ICON_IEFIRST_3              66
#define IDI_ICON_IEFIRST_1              67
#define IDI_ICON_IENEXT_2               68
#define IDI_ICON_IENEXT_3               69
#define IDI_ICON_IENEXT_1               70
#define IDI_ICON_IEPREV_2               71
#define IDI_ICON_IEPREV_3               72
#define IDB_BMP_VOLUMEMIC_1             75
#define IDB_BMP_VOLUMEMIC_2             76
#define IDB_BMP_VOLUMEMIC_3             77
#define IDB_BMP_VOLUMEMIC_4             78
#define IDB_BMP_VOLUMEEAR_1             79
#define IDB_BMP_VOLUMEEAR_2             80
#define IDB_BMP_VOLUMEEAR_3             81
#define IDB_BMP_VOLUMEEAR_4             82
#define IDB_BMP_WHISH_1                 83
#define IDB_BMP_WHISH_2                 84
#define IDB_BMP_WHISH_3                 85
#define IDB_BMP_WHISH_4                 86
#define IDB_BMP_NOWHISH_1               87
#define IDB_BMP_NOWHISH_2               88
#define IDB_BMP_NOWHISH_3               89
#define IDB_BMP_NOWHISH_4               90
#define IDI_ICON_PHONENUM_X_1           96
#define IDI_ICON_PHONENUM_0_1           97
#define IDI_ICON_PHONENUM_1_1           98
#define IDI_ICON_PHONENUM_2_1           99
#define IDI_ICON_PHONENUM_3_1           100
#define IDI_ICON_PHONENUM_4_1           101
#define IDI_ICON_PHONENUM_5_1           102
#define IDI_ICON_PHONENUM_6_1           103
#define IDI_ICON_PHONENUM_7_1           104
#define IDI_ICON_PHONENUM_8_1           105
#define IDI_ICON_PHONENUM_9_1           106
#define IDI_ICON_PHONENUM_J_1           107
#define IDB_BMP_PHONENUMLIST_3          124
#define IDB_BMP_PHONENUMLIST_1          125
#define IDB_BMP_PHONENUMLIST_2          126
#define IDI_ICON_CLEAR_1                168
#define IDI_ICON_BACKSPACE              169
#define IDI_ICON_BACKSPACE_1            170
#define IDI_ICON_CLEAR                  171
#define IDI_ICON_BACKSPACE_2            174
#define IDI_ICON_CLEAR_2                175
#define IDD_DLG_SYSTEMINFO_HISTORY      181
#define IDR_MENU_IE_TAB                 195
#define IDB_BMP_LOGIN_BG_EXPAND         196
#define IDB_BMP_LOGIN_BG                197
#define IDB_BMP_VOLUME                  198
#define IDB_BMP_PHONEKEYBOARD           199
#define IDB_BMP_TOOLBAR_SEPARATOR       200
#define IDD_DLG_TEXTCHAT                203
#define IDR_TOOLBAR_SYS_NORMAL          205
#define IDR_WAVE_QUEUING                206
#define IDR_WAVE_RING                   207
#define IDR_WAVE_DIAL                   208
#define IDR_TOOLBAR_SYS                 209
#define IDR_TOOLBAR_SYS_CCN             210
#define IDR_MENU_SYSTEMTRAY             211
#define IDD_UPDATE_TIP                  212
#define IDD_DLG_FREEAGENT               215
#define IDD_UPDATE_DOWN                 216
#define IDB_BMP_MAIN_WEB_4              218
#define IDB_BMP_MAIN_WEB_1              219
#define IDD_TAB_HEAD                    220
#define IDB_BMP_MAIN_WEB_2              220
#define IDR_IE_NEWPAGE_DROPMENU         221
#define IDB_BMP_MAIN_WEB_3              221
#define IDR_IE_HISTORY                  222
#define IDR_OUTDIAL                     224
#define IDD_DLG_SENDSMS                 225
#define IDD_DLG_TALKAGENT               226
#define IDR_WAV_HOLD                    227
#define IDR_WAV_DTMF                    228
#define IDD_DLGBAR_TOP                  230
#define IDD_DLGBAR_BOTTOM               232
#define IDD_DLG_VOLUME_MIC              233
#define IDD_DLGBAR_IE_TOOL              234
#define IDD_DLG_VOLUME_EARPHONE         235
#define IDD_DLG_PHONENUM_HISTROY        237
#define IDD_DLG_PHONE_KEYBOARD          238
#define IDD_DLG_MY_MSGBOX               239
#define IDD_DLG_LOGIN                   240
#define IDD_DLG_CONTACT_INFOBIRD        241
#define IDD_DLG_CALENDAR                242
#define IDI_ICON_IETOOLBAR_NEXT         243
#define IDR_MENU_PARK_REASONS           245
#define IDI_ICON_CHAT                   247
#define IDC_GOTO_URL                    250
#define IDI_ICON_DOC                    251
#define IDI_ICON_IETOOLBAR_PREV         253
#define IDI_ICON_IETOOLBAR_GOTO         254
#define IDI_ICON_IETOOLBAR_REFRESH      255
#define IDI_ICON_IETOOLBAR_STOP         256
#define IDI_ICON_PHONENUM_0             257
#define IDI_ICON_PHONENUM_1             258
#define IDI_ICON_PHONENUM_2             259
#define IDI_ICON_PHONENUM_3             260
#define IDI_ICON_PHONENUM_4             261
#define IDI_ICON_PHONENUM_5             262
#define IDI_ICON_PHONENUM_6             263
#define IDI_ICON_PHONENUM_7             264
#define IDB_BMP_SHOWWARN                264
#define IDI_ICON_PHONENUM_8             265
#define IDI_ICON_PHONENUM_9             266
#define IDI_ICON_PHONENUM_J             267
#define IDI_ICON_PHONENUM_X             268
#define IDD_DLG_ACDAUTOLOGIN            269
#define IDI_ICON_TOOLTIP                270
#define IDB_BMP_ACDAutoLogin            270
#define IDI_ICON_LOGO                   271
#define IDB_BMP_AUTOUPDATE              273
#define IDB_BMP_BG                      274
#define IDB_BMP_CHILDDLG_TITLE_BG       277
#define IDB_BMP_DELETE_DOWN             278
#define IDB_BMP_DELETE_UP               279
#define IDB_BMP_EARPHONE_DOWN           280
#define IDB_BMP_EARPHONE_UP             281
#define IDB_BMP_MIC_DOWN                282
#define IDD_DLG_LOCALRECORD             284
#define IDB_BMP_MIC_UP                  285
#define IDB_BMP_PHONEKEYBOARD_DOWN      288
#define IDB_BMP_PHONEKEYBOARD_UP        289
#define IDB_BMP_LAMP_PROCESS            292
#define IDB_BMP_LAMP_PARK               293
#define IDB_BMP_LAMP_TALK               294
#define IDB_BMP_LAMP_INCOMINGCALL       295
#define IDB_BMP_LAMP_HOLD               296
#define IDB_BMP_HOLD_1                  297
#define IDB_BMP_HOLD_2                  298
#define IDB_BMP_HOLD_3                  299
#define IDB_BMP_HOLD_4                  300
#define IDB_BMP_OUTDIAL_1               301
#define IDB_BMP_OUTDIAL_2               302
#define IDB_BMP_OUTDIAL_3               303
#define IDB_BMP_OUTDIAL_4               304
#define IDB_BMP_NOTE_3                  305
#define IDB_BMP_NOTE_1                  306
#define IDB_BMP_NOTE_2                  307
#define IDB_BMP_NOTE_4                  308
#define IDB_BMP_UNPARK_1                317
#define IDB_BMP_UNPARK_2                318
#define IDB_BMP_UNPARK_3                319
#define IDB_BMP_UNPARK_4                320
#define IDB_BMP_UNHOLD_1                321
#define IDB_BMP_UNHOLD_2                322
#define IDB_BMP_UNHOLD_3                323
#define IDB_BMP_UNHOLD_4                324
#define IDC_BTN_VOLUME_EARPHONE         325
#define IDC_STATIC_URL                  334
#define IDC_BTN_VOLUME_MIC              335
#define IDC_EXPLORER_URL                336
#define IDC_BTN_PHONEKEYBOARD           337
#define IDC_COMBO_DEVICE_AUDIO          338
#define IDB_BMP_UNPROCESS_1             339
#define IDB_BMP_UNPROCESS_2             340
#define IDB_BMP_UNPROCESS_3             341
#define IDB_BMP_UNPROCESS_4             342
#define IDC_COMBO_DEVICE_AUDIO_RENDERERS 344
#define IDB_BMP_NET_BAD                 345
#define IDC_TEXTCHAT_HIS                346
#define IDB_BMP_NET_VERYBAD             347
#define IDB_BMP_NET_BUSY                348
#define IDB_BMP_NET_GOOD                349
#define IDB_BMP_PARK_1                  350
#define IDB_BMP_PARK_2                  351
#define IDB_BMP_PARK_3                  352
#define IDB_BMP_PARK_4                  353
#define IDC_TEXTCHAT_SAY                354
#define IDC_BTN_PREV                    355
#define IDC_BTN_NEXT                    356
#define IDB_BMP_TRANSFER_1              357
#define IDB_BMP_TRANSFER_2              358
#define IDB_BMP_TRANSFER_3              359
#define IDB_BMP_TRANSFER_4              360
#define IDC_BTN_MINBAR                  365
#define IDB_BMP_ONHOOK_1                366
#define IDB_BMP_ONHOOK_2                367
#define IDB_BMP_ONHOOK_3                368
#define IDB_BMP_ONHOOK_4                369
#define IDB_BMP_TOOLBAR_RIGHT_BG        370
#define IDB_BMP_TITLE_CENTER_BG         371
#define IDB_BMP_TITLE_LEFT_BG           372
#define IDB_BMP_TITLE_RIGHT_BG          373
#define IDC_BTN_CLOSE                   374
#define IDB_BMP_TOOLBAR_LEFT_BG         375
#define IDB_BMP_TOOLBAR_FILL_BG         376
#define IDB_BMP_TITLE_FILL_BG           377
#define IDD_DLG_LOGIN_COMPANY           379
#define IDD_DLG_LOGIN_LOGINNAME         380
#define IDB_BMP_LOGIN_UP                381
#define IDB_BMP_LOGIN_DOWN              382
#define IDC_BTN_REFRESH                 383
#define IDC_BTN_STOP                    384
#define IDB_BMP_OFFHOOK_1               385
#define IDB_BMP_OFFHOOK_2               386
#define IDB_BMP_OFFHOOK_3               387
#define IDB_BMP_OFFHOOK_4               388
#define IDD_DLG_SETTINGS                389
#define IDB_BMP_HELP_1                  390
#define IDB_BMP_HELP_2                  391
#define IDB_BMP_HELP_3                  392
#define IDC_BTN_COPY_WEB_TEXT           393
#define IDB_BMP_PROCESS_1               394
#define IDB_BMP_PROCESS_2               395
#define IDB_BMP_PROCESS_3               396
#define IDB_BMP_PROCESS_4               397
#define IDC_EDIT_URL                    398
#define IDC_BTN_GOTO                    399
#define IDB_BMP_EXIT_1                  400
#define IDB_BMP_EXIT_2                  401
#define IDB_BMP_EXIT_3                  402
#define IDB_BMP_CLOSE_1                 403
#define IDB_BMP_CLOSE_2                 404
#define IDB_BMP_CLOSE_3                 405
#define IDB_BMP_MINIMIZE_1              406
#define IDB_BMP_MINIMIZE_2              407
#define IDB_BMP_MINIMIZE_3              408
#define IDC_EDIT_INFO_PANE              413
#define IDD_DLG_MY_SETTINGS             416
#define IDD_DLG_HELPTIP                 417
#define IDB_BMP_SETTINGS_1              418
#define IDB_BMP_SETTINGS_2              419
#define IDB_BMP_SETTINGS_3              420
#define IDB_BMP_SETTINGS_4              421
#define IDB_BMP_AUTOTRANSFER_1          422
#define IDB_BMP_AUTOTRANSFER_2          423
#define IDB_BMP_AUTOTRANSFER_3          424
#define IDB_BMP_AUTOTRANSFER_4          425
#define IDD_DLG_TRANSFER                426
#define IDI_ICON_HELPTIP                427
#define IDB_BMP_MAXIMIZE                436
#define IDC_STATIC_MAINTITLE            437
#define IDB_BMP_LAMP_OUTDIAL            438
#define IDB_BMP_LAMP_WAIT               439
#define IDB_BMP_LAMP_INCOMINGCALL_WINK  440
#define IDC_BTN_NUM_1                   441
#define IDC_BTN_NUM_2                   442
#define IDC_BTN_NUM_3                   443
#define IDC_BTN_NUM_4                   444
#define IDC_BTN_NUM_5                   445
#define IDC_BTN_NUM_6                   446
#define IDC_BTN_NUM_7                   447
#define IDC_BTN_NUM_8                   448
#define IDC_BTN_NUM_9                   449
#define IDC_BTN_NUM_X                   450
#define IDC_BTN_NUM_0                   451
#define IDC_BTN_NUM_J                   452
#define IDB_BMP_PHONEKEYBOARD_UP_1      455
#define IDB_BMP_PHONEKEYBOARD_DOWN_1    456
#define IDC_STATIC_PIC_STATUS           457
#define IDC_BTN_PHONENUM                458
#define IDC_BTN_CHAT                    459
#define IDC_STATIC_TIME_LENGTH          460
#define IDC_PIC_TITLE_CENTER_BG         461
#define IDC_CHK_SAVE_PASSWROD           463
#define IDC_PROGRESS                    464
#define IDC_STATIC_MSG                  465
#define IDC_LIST_FREEAGENT_COMPUTER     466
#define IDC_SMS_RESULT                  468
#define IDC_UPDATE_TIP                  469
#define IDC_MSG                         470
#define IDC_SHOW_MSG_BAR                471
#define IDC_STATIC_SPEED                472
#define IDC_STATIC_KBSEC                473
#define IDC_EDIT_TRANSFER_TARGETNUM     475
#define IDC_BTN_MONIT                   477
#define IDC_SMS_CONTENT                 478
#define IDC_BTN_UNMONIT                 478
#define IDC_BTN_OUTDIAL                 481
#define IDC_BTN_PARK                    483
#define IDC_BTN_ONHOOK                  485
#define IDC_BTN_OFFHOOK                 487
#define IDC_BTN_TRANSFER                488
#define IDC_BTN_NOTE                    491
#define IDC_NEXT                        493
#define IDC_BTN_PROCESS                 495
#define IDC_BTN_UNPROCESS               496
#define IDC_BTN_CONTACT_INFOBIRD        498
#define IDC_BTN_HOLD                    500
#define IDC_BTN_EXIT                    502
#define IDC_BTN_UNPARK                  504
#define IDC_BTN_UNHOLD                  506
#define IDC_PREV                        507
#define IDC_FIRST                       508
#define IDC_CLOSE_ALL                   510
#define IDC_LAST                        511
#define IDC_IE_TAB                      512
#define IDC_SEND_NUMBER                 514
#define IDC_LIST_TALK_AGENT             515
#define IDC_CHK_AUTO_OFFHOOK            516
#define IDC_EDIT_PHONENUM               518
#define IDC_STATIC_QUEUE                519
#define IDC_SLIDER_MIC                  520
#define IDC_STATIC_OUTDIAL_COUNT        521
#define IDC_CALENDAR_NOW                522
#define IDC_STATIC_PARK_COUNT           523
#define IDC_STATIC_AVG_CALL_TIMELENGTH  524
#define IDC_STATIC_AVG_PROCESS_TIMELENGTH 525
#define IDC_STATIC_CONTENT              528
#define IDC_STATIC_MYMSGBOX_TITLE       529
#define IDC_BTN_LOGIN                   530
#define IDC_EDIT_OLD_PASSWORD           531
#define IDC_EDIT_NEW_PASSWORD           532
#define IDC_EDIT_CONFIRM_PASSWORD       533
#define IDC_BTN_CHANGE_PASSWORD         534
#define IDC_EDIT_LOGIN_PASSWROD         535
#define IDC_BTN_CONFIRM                 536
#define IDC_BTN_CANCEL                  537
#define IDC_BTN_SEND                    538
#define IDC_STATIC_VER_MAIN             542
#define IDC_PIC_TITLE_LEFT_BG           543
#define IDC_PIC_TITLE_RIGHT_BG          544
#define IDC_PIC_TOOLBAR_LEFT_BG         545
#define IDC_SLIDER_EARPHONE             548
#define IDC_STATIC_NET_STATUS           549
#define IDC_BTN_PHONENUM_CLEAR          555
#define IDC_EDIT_COMPANY                565
#define IDC_BTN_COMPANY_DOWN            566
#define IDC_EDIT_LOGINNAME              567
#define IDC_BTN_LOGINNAME_DOWN          568
#define IDC_BTN_LOGINNAME_CLEAR         569
#define IDC_BTN_COMPANY_CLEAR           570
#define IDC_STATIC_SEPARATOR_1          571
#define IDC_STATIC_SEPARATOR_2          572
#define IDC_STATIC_IETOOLBAR_FRAME      576
#define IDC_BTN_MINIMIZE                577
#define IDC_BTN_NORMALSIZE              578
#define IDC_BTN_SETTINGS                579
#define IDC_EDIT_FIRST_URL              580
#define IDC_BTN_AUTOTRANSFER            581
#define IDC_EDIT_WEBMAIN_URL            581
#define IDC_BTN_TRANSFER_TO_IVR         582
#define IDC_CHK_LOGIN_WEBPSTN           583
#define IDC_PROGRESS_LOGIN              584
#define IDC_BTN_LOCALRECORD_HELP        585
#define IDC_BTN_INCOMINGCALL_HELP       586
#define IDC_STATIC_HELPTIP_TITLE        587
#define IDC_BTN_BEEP_HELP               588
#define IDC_STATIC_HELPTIP_CONTENT      589
#define IDC_BTN_HELPTIP_CLOSE           590
#define IDC_CHK_RECORDER_SAVE_LOCAL     591
#define IDC_CHK_PC_SPEAKER              592
#define IDC_CHK_AUTOTRANSFER            593
#define IDC_EDIT_AUTOTRANSFER           594
#define IDC_BTN_LOGIN_SETTING           595
#define IDC_LIST_TRANSFER_COMPUTER      596
#define IDC_LIST_TRANSFER_MOBILE        597
#define ID_OFFHOOK                      599
#define ID_PARK                         600
#define ID_PROCESS                      601
#define ID_TRANSFER                     602
#define ID_SETTINGS                     603
#define IDS_ACCOUNT                     604
#define ID_LOGOUT_AGENT                 605
#define ID_CHECK_ERROR                  606
#define ID_SEND_ERROR_LOG               607
#define ID_DEL_ERROR_LOG                608
#define ID_RESET                        609
#define ID_LOGIN                        610
#define ID_ONHOOK                       611
#define ID_OUTDIAL                      612
#define ID_PREPROCESS                   613
#define ID_HOLD                         614
#define ID_CALL_DEPARTMENT              615
#define ID_CALL_AGENT                   616
#define ID_CALL_OTHER_DEPARTMENT        617
#define ID_CALL_PSTN                    618
#define ID_CALL_OTHER_AGENT             619
#define ID_EXIT                         620
#define ID_LOGOUT                       621
#define ID_SYSTEM_TOOLBAR               622
#define ID_VIEW_PHONE_BAR               623
#define ID_VIEW_SYSTEMBAR               624
#define ID_VIEW_TEXTCHATBAR             625
#define IDS_INIT                        626
#define IDM_PHONE_KEYBOARD              627
#define IDS_PROCESS_UPDATE              628
#define IDS_UPDATE_FILE_ERROR           629
#define IDS_CHECK_NEW_VERSION           630
#define IDS_INPUT_ACCOUNT_MSG           631
#define IDS_INPUT_PASSWORD_MSG          632
#define IDS_LOGINING                    633
#define IDS_LOGON_AND_CHECK_VERSION     634
#define ID_OFFHOOK_BTN                  635
#define IDS_LONGIN_MSG_BAR              636
#define IDM_CLEAR_HISTORY               637
#define IDS_LOGIN_FAIL_MSG              638
#define IDS_LOGIN_FAIL                  639
#define IDS_LOGIN_FAIL_MSG_1            640
#define IDS_CHECK_VERSION_FINISH        641
#define IDS_CONNECT_NET_FAIL_MSG        642
#define IDS_UPDATE_FAIL                 643
#define IDS_CHECKING_VERSION            644
#define IDS_OPTION                      645
#define IDS_PASSWORD                    646
#define IDS_OK                          647
#define IDS_REG                         648
#define ID_SHOWME                       649
#define ID_TAB_S                        650
#define ID_IE_NEWPAGE                   651
#define ID_IE_BACKPAGE                  652
#define ID_IE_NEXTPAGE                  653
#define ID_IE_STOP                      654
#define ID_IE_REFRESH                   655
#define ID_IE_HOMEPAGE                  656
#define ID_IE_FAVORITY                  657
#define ID_IE_FONT                      658
#define ID_IE_FIND                      659
#define ID_IE_PRINT                     660
#define IDM_IE_NEW_NULL_PAGE            661
#define IDM_IE_NEW_CUR_PAGE             662
#define ID_NULL                         663
#define IDM_IE_FONT_LARGEST             664
#define IDM_IE_FONT_LARGE               665
#define IDM_IE_FONT_MEDIUM              666
#define IDM_IE_FONT_SMALL               667
#define IDM_IE_FONT_SMALLEST            668
#define IDM_IE_ADD_FAVOTIFY             669
#define IDM_IE_CLEANUP_FAVORITY         670
#define ID_AUTOTRANSFER                 671
#define ID_SMS                          672
#define ID_IE_ADDRESS_BAR               673
#define IDM_PHONE_MONIT                 674
#define IDM_FORCE_DISCONNECT            675
#define ID_STATUSBAR_ACCOUNT            676
#define ID_STATUSBAR_LOGINTIME          677
#define ID_STATUSBAR_STATUS             678
#define ID_STATUSBAR_QUEUE              679
#define ID_STATUSBAR_AUDIO              680
#define ID_AGENT_PHONE_BAR              681
#define ID_SYS_BAR                      682
#define IDS_TITLE                       683
#define IDS_VERSION                     684
#define IDS_AGENT                       685
#define IDS_CCN                         686
#define ID_MENU_ADD_FAVOURITEURL        687
#define ID_MENU_CLOSE_IE_PAGE           688
#define IDC_STATIC_LOGIN_BG_NORMAL      689
#define IDC_STATIC_LOGIN_BG_EXPAND      690
#define IDC_STATIC_STATUSBAR_FRAME      691
#define IDC_STATIC_CONTACT_INFOBIRD_TITLE 693
#define IDC_STATIC_FREEAGENT_TITLE      694
#define IDC_STATIC_SETTING_TITLE        695
#define IDC_STATIC_SMS_TITLE            696
#define IDC_STATIC_TEXTCHAT_TITLE       697
#define IDB_BMP_URLBAR_BG               702
#define IDB_BMP_IEBAR_BG                703
#define IDB_BMP_IEADDPAGE               704
#define IDI_ICON_IETOOLBAR_PREV_1       705
#define IDI_ICON_IETOOLBAR_NEXT_1       706
#define IDR_WAVE_USER_HANGUP            710
#define IDC_COMBO_LANGUAGE_TYPE         720
#define IDC_COMBO_OPERATION_TYPE        721
#define IDC_CHK_TRANSFER_TO_IVR         722
#define IDC_EDIT_TRANSFER_TO_IVR        723
#define IDC_STATIC_IVR_TITLE            724
#define IDC_BTN_SEND_IVR_UUIDATA        725
#define IDD_DLG_SVRMSGSHOW              726
#define IDC_EDIT_OUTDIAL_HEAD_1         727
#define IDC_EDIT_OUTDIAL_HEAD_2         728
#define IDC_RADIO_BEEP1                 729
#define IDC_RADIO_BEEP2                 730
#define IDC_RADIO_BEEP3                 731
#define IDC_RADIO_BEEP4                 732
#define IDC_EDIT_FREQ                   733
#define IDC_EDIT_DURA                   734
#define IDC_HTMLVIEW                    735
#define IDC_CHECK_SHOW                  736
#define IDC_BTN_WHISHT_TO_CLIENT        737
#define IDC_BTN_NOWHISHT_TO_CLIENT      738
#define IDC_AGENTPANELOCXCTRL           739
#define IDC_CHK_OUTDIAL_HEAD_1          744
#define IDC_CHK_OUTDIAL_HEAD_2          745
#define IDC_BTN_PHONEKEYBOARD_1         746
#define IDC_BTN_BACKSPACE               747
#define IDC_BTN_CLEAR                   748
#define IDC_BTN_RESET                   749
#define IDC_LIST_SYSTEMINFO_HISTORY     750
#define IDC_IPADDRESS_LOGINSERVER       751
#define IDC_EDIT_SENDER                 752
#define IDC_EDIT_MSGCONTENT             753
#define IDC_BTN_BEEP_LISTEN             754
#define IDC_BTN_TWICE_CHECK             756
#define IDD_DLG_MSGSHOW                 757
#define IDB_BMP_TWICE_CHECK_1           758
#define IDB_BMP_TWICE_CHECK_2           759
#define IDB_BMP_TWICE_CHECK_3           760
#define IDB_BMP_TWICE_CHECK_4           761
#define IDD_DLG_PRIVILEGE               762
#define IDC_COMBO_USERNAME              763
#define IDD_DLG_GROUPSELECT             763
#define IDC_EDIT_PASSWORD               764
#define IDC_STATIC_TITLE                765
#define IDD_DLG_OUTDIAL_AGENT           766
#define IDB_BMP_OUTDIAL_AGENT_CALL      767
#define IDI_ICON_OUTDIAL_AGENT_CLOSE    768
#define IDB_BMP_OUTDIAL_TITLEBG         769
#define IDB_BMP_OUTDIAL_AGENT_1         780
#define IDB_BMP_OUTDIAL_AGENT           781
#define IDC_SCROLLBAR_TEST              782
#define IDC_STATIC_TEST                 783
#define IDC_BTN_OUTDIAL_ANGENT_CLOSE    784
#define IDC_BTN_MAIN_WEB                785
#define IDC_LIST_GROUP                  786
#define IDC_BTN_OUTDIAL_AGENT           787
#define IDB_BMP_OUTDIAL_FREEDEPART      788
#define IDB_BMP_OUTDIAL_FREEAGENT       789
#define IDB_BMP_OUTDIAL_FREEAGENT_NORMAL 790
#define IDB_BMP_OUTDIAL_FREEDEPART_NORMAL 791
#define IDB_BMP_OUTDIAL_AGENT_2         800
#define IDC_STATIC_BG                   801
#define IDM_PARK_REASON_1               810
#define IDM_PARK_REASON_2               811
#define IDM_PARK_REASON_3               812
#define IDM_PARK_REASON_4               813
#define IDM_PARK_REASON_5               814
#define IDM_PARK_REASON_6               815
#define IDM_PARK_REASON_7               816
#define IDM_PARK_REASON_8               817
#define IDM_PARK_REASON_9               818
#define IDM_PARK_REASON_10              819
#define IDC_CHK_USERDEFINED_SERVER      820
#define IDC_CHK_USERDEFINED_WEBPAGE     821
#define IDC_CHK_USERDEFINED_WEBMAIN     822
#define IDB_BMP_MONIT_1                 830
#define IDB_BMP_MONIT_2                 831
#define IDB_BMP_MONIT_3                 832
#define IDB_BMP_MONIT_4                 833
#define IDB_BMP_UNMONIT_1               834
#define IDB_BMP_UNMONIT_2               835
#define IDB_BMP_UNMONIT_3               836
#define IDB_BMP_UNMONIT_4               837
#define IDC_PIC_NET_STATUS              838
#define IDB_BMP_JOINOUTDIAL_1           841
#define IDB_BMP_JOINOUTDIAL_2           842
#define IDB_BMP_JOINOUTDIAL_3           843
#define IDB_BMP_JOINOUTDIAL_4           844
#define IDB_BMP_EXITOUTDIAL_1           845
#define IDB_BMP_EXITOUTDIAL_2           846
#define IDB_BMP_EXITOUTDIAL_3           847
#define IDB_BMP_EXITOUTDIAL_4           848
#define IDC_BTN_JOINOUTDIAL             850
#define IDC_BTN_EXITOUTDIAL             851
#define IDD_DLG_SHOWWARN                852
#define IDC_EDIT_START_URL              853
#define IDC_BTN_STARTCONFERENCE         854
#define IDC_BTN_ENDCONFERENCE           855
#define IDB_BMP_LAMP_CONFERENCE         856
#define IDB_BMP_START_CONFERENCE1       857
#define IDB_BMP_START_CONFERENCE2       858
#define IDB_BMP_START_CONFERENCE3       859
#define IDB_BMP_START_CONFERENCE4       860
#define IDB_BMP_END_CONFERENCE1         861
#define IDB_BMP_END_CONFERENCE2         862
#define IDB_BMP_END_CONFERENCE3         863
#define IDB_BMP_END_CONFERENCE4         864
#define IDB_BMP_RESET_1                 865
#define IDB_BMP_RESET_2                 866
#define IDB_BMP_RESET_3                 867
#define IDB_BMP_RESET_4                 868
#define IDC_BTN_OFFPLAYAGENTID          870
#define IDB_BMP_OFFPLAYAGENTID1         871
#define IDB_BMP_OFFPLAYAGENTID2         872
#define IDB_BMP_OFFPLAYAGENTID3         873
#define IDB_BMP_OFFPLAYAGENTID4         874
#define IDC_BTN_SHOWWARN_CLOSE          876
#define IDC_STATIC_LOGINSETTING_TITLE   877
#define IDC_STATIC_ACDAUTOLOGIN         878
#define IDC_BTN_CLOSE_ACDAUTOLOGIN      890
#define IDC_STATIC_ACDAUTOLOGIN_TITLE   891
#define IDC_BTN_CHANGE_RECPATH          901
#define IDC_BTN_LOCAL_RECORD_CLOSE      902
#define IDC_STATIC_LOCAL_RECORD_TITLE   903
#define IDC_EDIT_LOCAL_RECORD_CONTENT   904
#define IDC_BTN_CAPTUREAUDIO_TEST       905
#define IDC_BTN_RENDERAUDIO_TEST        906
#define IDC_BUTTON_AUDIO_HELP           907
#define IDC_RADIO_BROWSER_IE            910
#define IDC_RADIO_BROWSER_CHROME        911
#define IDC_COMBO_BROWSER_IE_VERSIONS   912
#define IDC_CHECK_URLENCODE             36089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        286
#define _APS_NEXT_COMMAND_VALUE         36018
#define _APS_NEXT_CONTROL_VALUE         36090
#define _APS_NEXT_SYMED_VALUE           36009
#endif
#endif
